[package]
name = "cliraoke"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
serde = "1.0.219"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
rodio = "0.20.1"
yt-dlp = "1.2.3"
regex = "1.11.1"