[package]
name = "oke-doke"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
csv = "1.1"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
rodio = "0.17"
blocking = "1.6.1"